# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Hariharan Narayanan

[package]
name = "kaaryasoochi-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
chrono-tz = { version = "0.10", default-features = false }
serde.workspace = true
thiserror.workspace = true
